import React, { FC } from 'react'
import Head from 'next/head'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'

type Content = {
  children: any;
}

export const MainLayout: FC<Content> = ({children}) => {
    return (
        <>
          <Head>
            <title>Vasco Next</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />
    
          <main className={styles.main}>
            <div className={styles.grid}>
              {children}
            </div>
          </main>
        </>
      )
}
